/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.generia.tools.model.api.validation;

import org.eclipse.emf.common.util.EMap;
import de.generia.tools.model.api.EModelElement;

import java.util.Map;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.generia.tools.model.api.EAnnotation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EAnnotationValidator {
	boolean validate();

	boolean validateSource(String value);
	boolean validateDetails(EMap<String, String> value);

	boolean validateDetails(Map<?, ?> value);
	boolean validateModelElement(EModelElement value);

	boolean validateEModelElement(EModelElement value);
	boolean validateContents(EList<EModelElement> value);
	boolean validateReferences(EList<EModelElement> value);
}
