/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.generia.tools.model.api.validation;

import de.generia.tools.model.api.EClass;
import de.generia.tools.model.api.EClassifier;
import de.generia.tools.model.api.EOperation;
import de.generia.tools.model.api.EStructuralFeature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.generia.tools.model.api.EClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EClassValidator {
	boolean validate();

	boolean validateAbstract(Boolean value);

	boolean validateInterface(Boolean value);

	boolean validateAbstract(boolean value);
	boolean validateInterface(boolean value);
	boolean validateSuperType(EClass value);

	boolean validateSuperTypes(EClass value);

	boolean validateSuperTypes(EList<EClass> value);

	boolean validateStructuralFeatures(EList<EStructuralFeature> value);

	boolean validateOperations(EList<EOperation> value);

	boolean validateNestedClassifiers(EList<EClassifier> value);

	boolean validateESuperTypes(EList<EClass> value);
	boolean validateEStructuralFeatures(EList<EStructuralFeature> value);
	boolean validateEOperations(EList<EOperation> value);
	boolean validateENestedClassifiers(EList<EClassifier> value);
}
