/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.generia.tools.model.api.validation;

import de.generia.tools.model.api.EClass;
import de.generia.tools.model.api.EClassifier;
import de.generia.tools.model.api.EParameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.generia.tools.model.api.EOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EOperationValidator {
	boolean validate();

	boolean validateContainingClass(EClass value);

	boolean validateParameters(EList<EParameter> value);

	boolean validateExceptions(EList<EClassifier> value);

	boolean validateEContainingClass(EClass value);
	boolean validateEParameters(EList<EParameter> value);
	boolean validateEExceptions(EList<EClassifier> value);
}
