/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.generia.tools.model.api.validation;

import de.generia.tools.model.api.EAttribute;
import de.generia.tools.model.api.EClass;
import de.generia.tools.model.api.EReference;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.generia.tools.model.api.EReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EReferenceValidator {
	boolean validate();

	boolean validateContainment(Boolean value);

	boolean validateContainment(boolean value);
	boolean validateResolveProxies(boolean value);
	boolean validateOpposite(EReference value);

	boolean validateReferenceType(EClass value);

	boolean validateKeys(EList<EAttribute> value);

	boolean validateEOpposite(EReference value);
	boolean validateEReferenceType(EClass value);
	boolean validateEKeys(EList<EAttribute> value);
}
