/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.generia.tools.model.api.validation;

import de.generia.tools.model.api.EClassifier;

/**
 * A sample validator interface for {@link de.generia.tools.model.api.ETypedElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ETypedElementValidator {
	boolean validate();

	boolean validateOrdered(Boolean value);

	boolean validateMany(Boolean value);

	boolean validateRequired(Boolean value);

	boolean validateOrdered(boolean value);
	boolean validateUnique(boolean value);
	boolean validateMany(boolean value);
	boolean validateRequired(boolean value);
	boolean validateType(EClassifier value);

	boolean validateKeyType(EClassifier value);

	boolean validateEType(EClassifier value);
}
